import Head from 'next/head'
import SignupForm from '../components/authForms/SignupForm'

export default function Home() {
  return (
    <>
    <Head>
        <title>Foodie Hunter</title>
        
    
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/latest/css/bootstrap.min.css"/> */}

        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div >
      
      <SignupForm></SignupForm>

    </div>
    </>
  )
}
